<?php
// src/checkout-handler.php

// 1. Force absolute visibility into database anomalies
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

session_start();

// 2. Safely capture database context mapping
require_once __DIR__ . '/../config/database.php';

try {
    $db = DatabaseConnection::getMySQL();
    // Configure PDO to throw loud errors if SQL queries choke
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Exception $e) {
    die("Database Connection Initialization Failed: " . $e->getMessage());
}

// 3. Fallback Test Data Injector (If your frontend session arrays are unpopulated)
if (empty($_SESSION['cart'])) {
    // Generate an automatic development payload so your tables populate on click
    $_SESSION['cart'] = [
        ['id' => 1, 'price' => 299.99, 'quantity' => 2],
        ['id' => 3, 'price' => 1500.00, 'quantity' => 1]
    ];
}

try {
    // 4. Fire open database sequence container transaction
    $db->beginTransaction();

    // Map a strict fallback user context if authentication isn't stored locally yet
    $user_id = $_SESSION['user_id'] ?? null;
    if (!$user_id) {
        // Find or default to an active operational record from your users ledger
        $user_check = $db->query("SELECT id FROM users LIMIT 1")->fetch(PDO::FETCH_ASSOC);
        $user_id = $user_check ? $user_check['id'] : 1;
    }

    // Compute dynamic aggregate valuations across items matrix
    $total_amount = 0;
    foreach ($_SESSION['cart'] as $item) {
        $total_amount += ($item['price'] * $item['quantity']);
    }

    // 5. INSERT row target to master transaction table
    $order_sql = "INSERT INTO orders (user_id, total_amount, status, created_at, updated_at) 
                  VALUES (:user_id, :total_amount, 'success', NOW(), NOW())";
    
    $order_stmt = $db->prepare($order_sql);
    $order_stmt->execute([
        ':user_id'      => $user_id,
        ':total_amount' => $total_amount
    ]);

    // Gather tracking sequence ID generated by the engine
    $order_id = $db->lastInsertId();

    // 6. Loop and execute entries into granular structural line item matrix
    $item_sql = "INSERT INTO order_items (order_id, product_id, quantity, price_at_purchase, price) 
                 VALUES (:order_id, :product_id, :quantity, :price_at_purchase, :price)";
    
    $item_stmt = $db->prepare($item_sql);

    foreach ($_SESSION['cart'] as $item) {
        // Fallback variables to handle any variances in your array key keys
        $product_id = $item['id'] ?? $item['product_id'];
        $quantity   = $item['quantity'] ?? 1;
        $price      = $item['price'] ?? 0.00;

        $item_stmt->execute([
            ':order_id'          => $order_id,
            ':product_id'        => $product_id,
            ':quantity'          => $quantity,
            ':price_at_purchase' => $price,
            ':price'             => $price
        ]);
    }

    // 7. Commit changes to physical disk layers safely
    $db->commit();

    // Wipe temporary cart payload structures
    unset($_SESSION['cart']);

    // Redirect cleanly back to center interface dashboard layout 
    header("Location: ../public/admin/dashboard.php?sync=ready");
    exit;

} catch (PDOException $e) {
    // Drop transaction safely to prevent corruption if parsing exceptions explode
    if ($db->inTransaction()) {
        $db->rollBack();
    }
    
    // Output comprehensive debugger data string directly to screen
    echo "<div style='background:#1e293b; color:#f43f5e; padding:30px; font-family:monospace; border-radius:8px; margin:40px; border:1px solid #f43f5e;'>";
    echo "<h3 style='margin-top:0; text-transform:uppercase;'>Procurement SQL Layer Crash Detected</h3>";
    echo "<strong>Error Message:</strong> " . htmlspecialchars($e->getMessage()) . "<br><br>";
    echo "<strong>Line Number:</strong> " . $e->getLine() . "<br><br>";
    echo "<strong>Stack Trace Output:</strong><pre style='color:#94a3b8; font-size:0.85rem;'>" . htmlspecialchars($e->getTraceAsString()) . "</pre>";
    echo "</div>";
    exit;
}